#!/bin/bash -x
scr_nm=fn_breakpoint

## Usage:   _xbp [ |+|x|e]
function _xbp() 
{
  case "$#" in 
    0 )
      : '$# = 0'
      : $LINENO
      return
      ;;
    1 )
      : '$# = 1'
      case "$1" in
        - )
          : '$1 = -'
          : $LINENO
          set +x
          ;;
        x )
          : '$1 = x'
          : $LINENO
          set -x
          ;;
        e|* )
          : '$1 = e'
          printf '%s: _xbp: line: %d\n' "$scr_nm" "$LINENO"
          exit 101
          ;;
      esac
      ;;
  esac
}


# action            noop    xon   xoff    exit

# from state xon    >xon   >xon   >xoff   >exit

# from state xoff   >xoff  >xon   >xoff   >exit


# Changes

echo one, line:$LINENO

#   xoff  A:xon   > xon
_xbp x

echo two, line:$LINENO

#   xon   A:noop  > xon
_xbp 

echo three, line:$LINENO

#   xon   A:xoff  > xoff
_xbp +

echo four, line:$LINENO

#   xoff  A:noop  > xoff
_xbp 

echo five, line:$LINENO

#   xoff  A:exit  > exit
_xbp e

echo six, line:$LINENO

#   xoff  A:xon   > xon
_xbp x

echo seven, line:$LINENO

#   xon   A:exit  > exit
_xbp e

echo eight, line:$LINENO

    


