#!/bin/bash -x
scr_nm=fn_breakpoint

## Usage:   _xbp [ |+|x|e]
function _xbp() 
{
  :
  case "$#" in 
    0 )
      : _xbp: NO-OP '$# = 0', line:$LINENO
      return
      ;;
    1 )
      : _xbp: '$# = 1', line:$LINENO
      case "$1" in
        - )
          : _xbp: XTRACE __ON__ '$1 = -', line:$LINENO
          set +x
          ;;
        x )
          : _xbp: XTRACE _OFF_'$1 = x', line:$LINENO
          set -x
          ;;
        e|* )
          : _xbp: EXIT '$1 = e', line:$LINENO
          printf '%s: _xbp: line: %d\n' "$scr_nm" "$LINENO"
          exit 101
          ;;
      esac
      ;;
  esac
}


# action            noop    xon   xoff    exit

# from state xon    >xon   >xon   >xoff   >exit

# from state xoff   >xoff  >xon   >xoff   >exit


# Changes

echo global, one, line:$LINENO

#   xoff  A:xon   > xon
_xbp x

echo global, two, line:$LINENO

#   xon   A:noop  > xon
_xbp 

echo global, three, line:$LINENO

#   xon   A:xoff  > xoff
_xbp +

echo global, four, line:$LINENO

#   xoff  A:noop  > xoff
_xbp 

echo global, five, line:$LINENO

#   xoff  A:exit  > exit
_xbp e

echo global, six, line:$LINENO

#   xoff  A:xon   > xon
_xbp x

echo global, seven, line:$LINENO

#   xon   A:exit  > exit
_xbp e


echo global, eight, line:$LINENO

    


