#!/bin/bash -eux

## Note, in case statements, the patterns can span more than one line. You just have to put a pipe
#+  immediately before the backslash at the end of the line

: 'Define rm()'
rm ()
{
  :;: 'Input must exist'
  (( ${#@} == 0 )) && return $LINENO
    
  ::: 'Vars'
  local - HH delete_d time_sfx args_rm
  delete_d=~/rm.d
  time_sfx=$(date --utc +%s)

  :;: '"Recycle bin" must exist'
  if ! [[ -e ${delete_d} ]] || ! [[ -d ${delete_d} ]]
  then
      mkdir --mode 0700 --verbose -- "${delete_d}" || return $LINENO
  fi

  :;: 'Process posparms'
  for HH
  do
    : 'For each FSO to be recycled'
    if [[ ${end_of_options:=} = 'has_been_reached' ]]
    then
      : 'Options are over'
      
      if [[ -e ${HH} ]]
      then
        args_rm+=( "${HH}" )
      else
        printf '\n\tInvalid imput, %s\n\n' "${HH}"
      fi
    else
      : 'Static options'
      case "${HH}" in
        -f|--force|-i|--interactive|--interactive=always|-I|--interactive=once|--interactive=never|\
        --one-file-system|--no-preserve-root|--preserve-root=all|-r|-R|--recursive|-d|--dir|-v|\
        --verbose|-- )
          args_rm+=( "${HH}" )
          ;;    
        --help )
          command rm --help
          ;;
        --version )
          command rm --version
          ;;
        * )
          : 'Non-option arguments'
          end_of_options='has_been_reached'
          
          case "${HH}" in
            * )
              if [[ -e ${HH} ]]
              then
                args_rm+=( "${HH}" )
              else
                printf '\n\tInvalid imput, %s\n\n' "${HH}"
              fi
              ;;
          esac
          ;;
      esac
    fi
  done

  : 'Sanity check for options and arguments'

    declare -p args_rm
    exit $LINENO

  : 'If optargs exist, then  mv  the file into the recycle bucket'
  if [[ -n ${args_rm[*]:0:8} ]]
  then
    builtin command -- mv --backup --suffix=".${time_sfx}" -- "${HH}" "${delete_d}" || return $LINENO
  fi
}
declare -fx rm

touch foo 
#touch bar baz quux

## Command      ## Syntax
#rm foo         ##  succeeds

#rm -f foo       ##  okay
rm foo -f       ## 
#rm -- foo       ## 
#rm foo --       ## 

#rm -f -- foo    ## 
#rm -- -f foo    ## 
#rm -f foo --    ## 
#rm foo -f --    ## 
#rm foo -- -f    ## 
#rm -- foo -f    ## 

