#!/bin/bash -eux

## Note, in case statements, the patterns can span more than one line. You just have to put a pipe
#+  immediately before the backslash at the end of the line

: 'Define rm()'
rm ()
{
  local -
  #set -
  
  :;: 'Input must exist'
  [[ ${#@} -eq 0 ]] && return "$LINENO"
    
  :;: 'For each positional parameter'
  local HH args_rm

  for HH
  do
    : 'If "End of Options" has been reached'
    if [[ ${end_of_options:=} = 'has_been_reached' ]]
    then
      : 'Options are over and only arguments are processed'
      
      if [[ -e ${HH} ]]
      then
        args_rm+=( "${HH}" )
      else
        printf '\n\tInvalid imput, %s\n\n' "${HH}"
        return "$LINENO"
      fi
    else
      : 'Options continue and arguments aren\x27t yet processed'
      : 'Static options'
      case "${HH}" in
        --version )
          command rm --version
          ;;
        --help )
          command rm --help
          ;;
        -- )
          end_of_options='has_been_reached'
          args_rm+=( "${HH}" )
          ;;    
        -f|--force|-i|--interactive|--interactive=always|-I|--interactive=once|--interactive=never|\
        --one-file-system|--no-preserve-root|--preserve-root=all|-r|-R|--recursive|-d|--dir|-v|\
        --verbose )
          args_rm+=( "${HH}" )
          ;;    
        * )
          : 'Non-option arguments'
          end_of_options='has_been_reached'
          
          case "${HH}" in
            * )
              if [[ -e ${HH} ]]
              then
                args_rm+=( "${HH}" )
              else
                printf '\n\tInvalid imput, %s\n\n' "${HH}"
              fi
              ;;
          esac
          ;;
      esac
    fi
  done

  : 'Sanity check for options and arguments'

    declare -p args_rm
    exit $LINENO

  :;: '"Recycle bin" must exist'
  local delete_d 
  delete_d=~/rm.d

  if ! [[ -e ${delete_d} ]] || ! [[ -d ${delete_d} ]]
  then
      mkdir --mode 0700 --verbose -- "${delete_d}" || return $LINENO
  fi

  : 'If optargs exist, then  mv  the file into the recycle bucket'
  local time_sfx 
  time_sfx=$( date --utc +%s )

  if [[ -n ${args_rm[*]:0:8} ]]
  then
    builtin command -- mv --backup --suffix=".${time_sfx}" -- "${HH}" "${delete_d}" || return $LINENO
  fi
}
declare -fx rm

touch foo 

## Command      ## Syntax
rm foo         ##  succeeds == okay

#rm -f foo       ##  succeeds == okay
#rm foo -f       ## Invalid imput == okay
#rm -- foo       ## 
#rm foo --       ## 

#rm -f -- foo    ## 
#rm -- -f foo    ## 
#rm -f foo --    ## 
#rm foo -f --    ## 
#rm foo -- -f    ## 
#rm -- foo -f    ## 

#touch bar baz quux


