#!/bin/bash -x
## Trying to write an 'echo()' function that will only print one line to xtrace whether xtrace is either on or off

#echo ()
#{
#  if [[ -o xtrace ]]
#  then
#    : "$@"
#  else
#    builtin echo "$@"
#  fi
#}


: 'Define set()' 
function set() {
  builtin set "$@"
   
  if [[ -o xtrace ]]
  then
    : 'Define echo() -- true'
    function echo(){
      #: "$@"
    }
  else
    : 'Define echo() -- builtin'
    function echo(){
      builtin echo "$@"
    }
  fi
}

set -x

echo foo 

echo bar

set +x

echo baz

echo quux

