#!/bin/bash -eux

## Q: Will line numbers print correctly?

declare -n nL=LINENO

function er_x()
{
  local - fn_exit_code=$?
  : "$@"
  return "${fn_exit_code}"
}

shopt -s expand_aliases
alias alias_erx='er_x "line ${nL}"'

function foo()
{
  local -
  : 'Printed strings, ie, no aliases'
  (( $#                             == 0 )) && er_x "line ${nL}"
  : 'Using alias'
  (( $#                             == 0 )) && alias_erx
  echo count $#
}

foo

