#!/bin/env -S bash -x -v
#set -x

## Tests:
#+    #!/bin/env -S bash -vx
#+    # set -vx"

#+    #!/bin/env -S bash -v
#+

#+    #!/bin/env -S bash -x
#+


## `man bash`: "-v      Print shell input lines as they are read."




echo '#####################################################'




## `help export`: "-p	display a list of all exported variables and functions"
## `man bash`: "If no names are given, or if the -p option is supplied, a list of names of all exported 
#+  variables is printed."
#export -p ; echo $?

#export | wc ; echo $?



## `help export`: "-f	refer to shell functions
