#!/bin/env -S bash -vx

## Tests:
#+  "#!/bin/env -S bash -vx"
#+  "#!/bin/env -S bash -v"
#+  "#!/bin/env -S bash -x"


echo '#####################################################'




## `help export`: "-p	display a list of all exported variables and functions"
## `man bash`: "If no names are given, or if the -p option is supplied, a list of names of all exported 
#+  variables is printed."
export -p ; echo $?

export | w ; echo $?c


## `help export`: "-f	refer to shell functions
